### ISSUE TITLE
Repetitive library code

### ISSUE THREAD

**Issue by EdJoPaTo** [ayrat555/frankenstein#28]
When looking in the huge `object.rs` or `api_params.rs` files they have always the same pattern: structs with impl to set / read values.

The function to read values doesn't seem very helpful as the value itself is marked as `pub` already in the struct. Some of them return cloned values which might be helpful for convenience but `user.last_name.clone()` isn't much different than `user.last_name()` and a way more explicit clone.

Setting these values feels semi useful currently. Both is possible currently:
```rs
let mut user = User::new(…);
user.set_username(None);
```

```rs
let mut user = User::new(…);
user.username = None;
```

Using the method does not provide much benefit currently. (Am I overlooking something?)

Maybe with the builder pattern these methods could be a bit more useful as it would allow for method chaining. Crates like [typed-builder](https://crates.io/crates/typed-builder) can help with creating such structure without much overhead. This would result in way less repetitive code.

Even when removing the set / get functions the library without adding some other logic the library would still be very useful but with way less repetitive code.

(This is mainly something I noticed and up for discussion)

**Comment by ayrat555** [comment]
@EdJoPaTo it's a reasonable issue. 

1. files are too big and in my opinion, they should be separated into separate files 
I have it in my backlog - https://braindump.badykov.com/notes/20210830183352-frankenstein/

2. Initially, I tried using `typed-builder` but I think I encountered an issue that made it impossible to use for all structs. I don't remember now. But we can try again I think

3. In the first version of the library fields were private, but people proposed to make them public. Also, it makes docs more useful because people can see all fields


any help is appreciated

**Comment by EdJoPaTo** [comment]
> In the first version of the library fields were private, but people proposed to make them public

I assumed something like this. I guess this can be splitted into two things:
- Remove the get / set methods which simplifies a lot (still a breaking change)
- Maybe add `typed-builder` if someone is interested in using it.

**Comment by ayrat555** [comment]
sounds good to me

**Comment by ayrat555** [comment]
resolved by https://github.com/ayrat555/frankenstein/pull/34
