### ISSUE TITLE
Error 500 on get_updates

### ISSUE THREAD

**Issue by hugorplobo** [ayrat555/frankenstein#60]
Hi, I'm getting some error 500 when trying to use get_updates in my code. My code is the same as the example reply_to_message_updates, and this is the error I get.

![image](https://user-images.githubusercontent.com/53958114/165382173-8f098509-9990-46e2-9e61-03c17b08b39b.png)

Can someone help me?

**Comment by EdJoPaTo** [comment]
The image contains your API token: Make sure to reset it so no one is able to use it.

Error 5xx are server side errors → The server does seem to have a problem here and not the library you are using. If the library does something wrong a 4xx error would be the case.

I assume this error should be gone after the issue is fixed server side.

**Comment by hugorplobo** [comment]
Yes i revoked it, thank you. I tried using a javascript library with the same token to see if it could be something on the telegram server but the bot worked correctly so i opened the issue.

**Comment by hugorplobo** [comment]
I started the bot again and now it's working. Maybe it was just luck that it worked one time and not the other.
