### ISSUE TITLE
Support for Tokio?

### ISSUE THREAD

**Issue by PirosB3** [ayrat555/frankenstein#7]
Awesome library! I'm using it for my project. Just curious, is there any non-blocking async API that supports Tokio?

**Comment by ayrat555** [comment]
@PirosB3 can you please clarify a little more?  Do you want API methods to be async so you can execute them in tokio tasks with `tokio::spawn`?

In this case, you can just create wrappers for API functions.

```rust
async fn send_message(api: Api, params: SendMessageParams) {
  api.send_message(params);
}
```

or do you want to use hyper/reqwest as an HTTP client?
Since the library uses a trait to define the Telegram interface, it's not possible to use async functions in traits. So you'll have to use the blocking client - https://github.com/seanmonstar/reqwest#blocking-client

**Comment by ayrat555** [comment]
@PirosB3 @arkada38 Hello.  I added a proper async client

It's included into an optional feature,  please check out the README
https://github.com/ayrat555/frankenstein#optional-features
